#!/usr/bin/env swift
//
// Draws CodeCat's app icon and writes Resources/AppIcon.png (1024×1024) plus
// Resources/CodeCat.icns.
//
//   swift scripts/make-icon.swift
//
// The cat is the same hand-drawn cat as `CatView.swift`, in its resting pose:
// same proportions, same two colours, same ear triangles and arc-shaped eyes.
// It is redrawn here in Core Graphics rather than rendered from the SwiftUI view
// because `CatView` lives inside the app target — importing it would mean
// building and launching the app to produce a file the build itself needs.
// The trade is that the two can drift; they are ~40 lines of shapes each, and
// the icon is regenerated by running this script, not by the build.
//
// This is placeholder artwork in the honest sense: it is the product's own cat at
// icon scale, not a designed mark. Replacing it means replacing AppIcon.png and
// re-running `iconutil`; nothing else in the build knows what the cat looks like.

import Foundation
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers

// MARK: - Palette

/// #E8A04C — the resting body colour from `CatView.bodyColor`.
let body = CGColor(red: 0.91, green: 0.63, blue: 0.30, alpha: 1)
/// The face colour from `CatView.dark`.
let dark = CGColor(red: 0.23, green: 0.16, blue: 0.09, alpha: 1)
/// The tile. Deliberately not `dark`: the face marks have to stay legible
/// against it, so the ground is a step deeper than the ink drawn on top of it.
let tileTop = CGColor(red: 0.20, green: 0.16, blue: 0.11, alpha: 1)
let tileBottom = CGColor(red: 0.11, green: 0.09, blue: 0.06, alpha: 1)

// MARK: - The cat, in CatView's own ~96pt coordinate space (y grows downward)

/// Bounding box of everything drawn below, measured from the shapes themselves —
/// body 50×52 at y+20, head Ø44 at y−14, ears at y−34, tail centred at (30, 34).
let contentBox = CGRect(x: -25, y: -41, width: 72, height: 87)

func capsulePath(center: CGPoint, width: CGFloat, height: CGFloat,
                 rotatedBy degrees: CGFloat, aboutLeadingEdge: Bool) -> CGPath {
    let rect = CGRect(x: center.x - width / 2, y: center.y - height / 2,
                      width: width, height: height)
    let pivot = aboutLeadingEdge ? CGPoint(x: rect.minX, y: rect.midY) : center
    var t = CGAffineTransform(translationX: pivot.x, y: pivot.y)
        .rotated(by: degrees * .pi / 180)
        .translatedBy(x: -pivot.x, y: -pivot.y)
    return CGPath(roundedRect: rect, cornerWidth: height / 2, cornerHeight: height / 2,
                  transform: &t)
}

/// `CatView.Triangle`: apex at the top edge's midpoint, base along the bottom.
func trianglePath(center: CGPoint, width: CGFloat, height: CGFloat, upsideDown: Bool) -> CGPath {
    let r = CGRect(x: center.x - width / 2, y: center.y - height / 2,
                   width: width, height: height)
    let p = CGMutablePath()
    if upsideDown {
        p.move(to: CGPoint(x: r.midX, y: r.maxY))
        p.addLine(to: CGPoint(x: r.maxX, y: r.minY))
        p.addLine(to: CGPoint(x: r.minX, y: r.minY))
    } else {
        p.move(to: CGPoint(x: r.midX, y: r.minY))
        p.addLine(to: CGPoint(x: r.maxX, y: r.maxY))
        p.addLine(to: CGPoint(x: r.minX, y: r.maxY))
    }
    p.closeSubpath()
    return p
}

/// `CatView.happyEye`: a shallow arc, drawn as a stroke rather than a fill.
func happyEyePath(at c: CGPoint) -> CGPath {
    let p = CGMutablePath()
    p.move(to: CGPoint(x: c.x - 4, y: c.y + 1))
    p.addQuadCurve(to: CGPoint(x: c.x + 4, y: c.y + 1), control: CGPoint(x: c.x, y: c.y - 3))
    return p
}

func drawCat(in ctx: CGContext) {
    // Tail, at the resting angle (`CatView.tailView`, the non-working branch).
    ctx.setFillColor(body)
    ctx.addPath(capsulePath(center: CGPoint(x: 30, y: 34), width: 34, height: 9,
                            rotatedBy: 4, aboutLeadingEdge: true))
    ctx.fillPath()

    // Body.
    ctx.addEllipse(in: CGRect(x: -25, y: -6, width: 50, height: 52))
    ctx.fillPath()

    // Ears first, so the head circle covers their bases.
    for x in [CGFloat(-15), 15] {
        ctx.addPath(trianglePath(center: CGPoint(x: x, y: -34), width: 16, height: 14,
                                 upsideDown: false))
    }
    ctx.fillPath()

    // Head.
    ctx.addEllipse(in: CGRect(x: -22, y: -36, width: 44, height: 44))
    ctx.fillPath()

    // Face: two content arcs and a nose.
    ctx.setStrokeColor(dark)
    ctx.setLineWidth(1.9)
    ctx.setLineCap(.round)
    for x in [CGFloat(-8), 8] { ctx.addPath(happyEyePath(at: CGPoint(x: x, y: -16))) }
    ctx.strokePath()

    ctx.setFillColor(dark)
    ctx.addPath(trianglePath(center: CGPoint(x: 0, y: -8), width: 7, height: 5, upsideDown: true))
    ctx.fillPath()
}

// MARK: - The tile

func render(size: Int) -> CGImage {
    let n = CGFloat(size)
    let ctx = CGContext(data: nil, width: size, height: size, bitsPerComponent: 8,
                        bytesPerRow: 0, space: CGColorSpaceCreateDeviceRGB(),
                        bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!

    // macOS icons are a rounded square inset inside a transparent canvas — the
    // inset is what keeps them optically the same size as every other icon in the
    // Dock. 824/1024 side with a 185/1024 corner is Apple's current proportion.
    let inset = n * 100 / 1024
    let tile = CGRect(x: inset, y: inset, width: n - 2 * inset, height: n - 2 * inset)
    let corner = n * 185 / 1024
    let tilePath = CGPath(roundedRect: tile, cornerWidth: corner, cornerHeight: corner,
                          transform: nil)
    ctx.saveGState()
    ctx.addPath(tilePath)
    ctx.clip()
    let gradient = CGGradient(colorsSpace: CGColorSpaceCreateDeviceRGB(),
                              colors: [tileTop, tileBottom] as CFArray,
                              locations: [0, 1])!
    ctx.drawLinearGradient(gradient,
                           start: CGPoint(x: 0, y: tile.maxY),
                           end: CGPoint(x: 0, y: tile.minY),
                           options: [])
    ctx.restoreGState()

    // The cat, fitted into the tile with room to breathe, and centred on its own
    // measured bounding box rather than on the origin of CatView's canvas — the
    // drawing is not symmetric about it (the tail reaches right).
    let padding = tile.width * 0.16
    let available = tile.width - 2 * padding
    let scale = min(available / contentBox.width, available / contentBox.height)
    ctx.saveGState()
    ctx.translateBy(x: tile.midX, y: tile.midY)
    ctx.scaleBy(x: scale, y: -scale)          // flip: CatView's y grows downward
    ctx.translateBy(x: -contentBox.midX, y: -contentBox.midY)
    drawCat(in: ctx)
    ctx.restoreGState()

    return ctx.makeImage()!
}

func write(_ image: CGImage, to url: URL) {
    let dest = CGImageDestinationCreateWithURL(url as CFURL, UTType.png.identifier as CFString, 1, nil)!
    CGImageDestinationAddImage(dest, image, nil)
    guard CGImageDestinationFinalize(dest) else {
        FileHandle.standardError.write(Data("could not write \(url.path)\n".utf8))
        exit(1)
    }
}

// MARK: - Output

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let resources = root.appendingPathComponent("Resources")
guard FileManager.default.fileExists(atPath: resources.path) else {
    FileHandle.standardError.write(Data("run this from the repository root\n".utf8))
    exit(1)
}

write(render(size: 1024), to: resources.appendingPathComponent("AppIcon.png"))

// .iconset → iconutil. Every size Apple asks for, including the @2x variants:
// iconutil rejects an incomplete set rather than filling the gaps itself.
let iconset = resources.appendingPathComponent("CodeCat.iconset")
try? FileManager.default.removeItem(at: iconset)
try! FileManager.default.createDirectory(at: iconset, withIntermediateDirectories: true)
for base in [16, 32, 128, 256, 512] {
    write(render(size: base), to: iconset.appendingPathComponent("icon_\(base)x\(base).png"))
    write(render(size: base * 2), to: iconset.appendingPathComponent("icon_\(base)x\(base)@2x.png"))
}

let iconutil = Process()
iconutil.executableURL = URL(fileURLWithPath: "/usr/bin/iconutil")
iconutil.arguments = ["-c", "icns", iconset.path,
                      "-o", resources.appendingPathComponent("CodeCat.icns").path]
try! iconutil.run()
iconutil.waitUntilExit()
guard iconutil.terminationStatus == 0 else { exit(iconutil.terminationStatus) }
try? FileManager.default.removeItem(at: iconset)

print("wrote Resources/AppIcon.png and Resources/CodeCat.icns")
